' This code has been generated by AI. Original prompt:
' read excel file
Dim objExcel, objWorkbook, objSheet
Dim row, col, cellValue

' Create an instance of Excel application
Set objExcel = CreateObject("Excel.Application")

' Open the Excel file
Set objWorkbook = objExcel.Workbooks.Open("${filePath}")

' Select the first sheet (you can change the index to select a different sheet)
Set objSheet = objWorkbook.Sheets(3)

' Loop through each row and column to read the cell values
For row = 1 To objSheet.UsedRange.Rows.Count
    For col = 1 To objSheet.UsedRange.Columns.Count
        cellValue = objSheet.Cells(row, col).Value
        WScript.Echo "Row: " & row & " Column: " & col & " Value: " & cellValue
    Next
Next

' Close the workbook without saving
objWorkbook.Close False

' Quit the Excel application
objExcel.Quit

' Release the objects
Set objSheet = Nothing
Set objWorkbook = Nothing
Set objExcel = Nothing